spring:
  application:
    name: msvc-course
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Config for health probes
management.endpoint.health.probes.enabled: true

