server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/course/**
        - id: auth
          uri: 'http://localhost:9091'
          predicates:
            - Path=/api/auth/**
  output:
    ansi:
      enabled: always
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}


